declare module '*.png';
declare module '*.jpg';
declare module '*.jpeg';
declare module '*.bmp';
declare module '*.gif';
declare module '*.webp';
declare module '*.psd';
declare module '*.html';
declare module '*.css';